Created 3 new instance scan checks (Table Check) & Updated the README.md document.
ServiceNowDevProgram/example-instancescan-checks pull request #171
Opened 2024-10-30 20:28 UTC by vijaytalupula

a) Created THREE new instance scan checks of the class type "Table Check" as follows,

   Manageability:
       1. Always keep code/snippet in functions - Business Rules.
       2. Update set In Progress/Completed previously Ignored.

   Performance:
      1. Catalog Client script with GlideRecord API calls.

b) Updated the README.md document as well for the same.

2024-10-31 06:51 UTC, SapphicFire requested changes
Thank you for your contribution. However, two of the checks do not behave as documented. Please review the files you have changed/added and ensure that all modifications are correct.

2024-10-31 06:51 UTC, SapphicFire commented on ca8467c41b9abc10ce0f62c3b24bcbaa/update/scan_table_check_03173371c3a19610afa6fc84e40131af.xml
This does not validate whether the code is enclosed in a function. This looks for the text function. I could write a comment such as:

```js
// I hope this code functions as expected
```

and it would match the value. I recommend removing this one so we can accept this PR, and then submitting a separate one that users a linter check to validate this behaviour

2024-10-31 06:51 UTC, SapphicFire commented on ca8467c41b9abc10ce0f62c3b24bcbaa/update/scan_table_check_a8d2377dc3619610afa6fc84e4013135.xml
This does not validate whether the GlideRecord object is used. This looks for the text GlideRecord. I could write a comment such as:

```js
// Using GlideAjax instead of GlideRecord as requested
```

and it would match the value. I recommend removing this one so we can accept this PR, and then submitting a separate one that users a linter check to validate this behaviour

2024-11-01 05:45 UTC, closed without merging

2024-11-01 05:46 UTC, vijaytalupula commented
Thanks for your review and feedback @SapphicFire. I have created a new branch with new pull request.